# Generated by Django 4.2.30 on 2026-06-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('attendance_pct', models.FloatField(default=80.0, help_text='Attendance percentage (0-100)')),
                ('study_hours_per_week', models.IntegerField(default=10, help_text='Weekly study hours')),
                ('predicted_status', models.CharField(choices=[('Pass', 'Pass'), ('At-Risk', 'At-Risk'), ('Fail', 'Fail'), ('Not Predicted', 'Not Predicted')], default='Not Predicted', max_length=20)),
                ('prediction_confidence', models.FloatField(default=0.0, help_text='Confidence percentage (0-100)')),
                ('prediction_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
